spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    active: dev
  h2:
    console:
      enabled: true
quartz:
  enabled: true

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.xml

