spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: javadoc
      host: localhost
      port: 27017
      password:
      repositories:
        enabled: true

quartz:
  enabled: false

ushi:
  nexus:
    url: http://nexus.qjdchina.com/nexus/
  javadoc:
    output: /tmp/javadoc/
