spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: javadoc
      host: localhost
      port: 27017
      password:
      repositories:
        enabled: true

quartz:
  enabled: true
